### ISSUE TITLE
What is the correct format for electricityReadings time?

### ISSUE THREAD

**Issue by haohaolee** [thoughtworks-hpc/developer_joiyofenergy_cpp#2]
According to the readme, it is Epoch timestam

> The date/time (as epoch) when the reading was taken

But this will crash the server by an exception `nlohmann::detail::type_error` `type must be string, but is number`
Seems the code accepts only rfc3339.

**Comment by haohaolee** [comment]
The test payload is taken from readme:
```
$ curl \
  -X POST \
  -H "Content-Type: application/json" \
  "http://localhost:8080/readings/store" \
  -d '{"smartMeterId":"smart-meter-0","electricityReadings":[{"time":1606636800,"reading":0.0503},{"time":1606636860,"reading":0.0621},{"time":1606636920,"reading":0.0222},{"time":1606636980,"reading":0.0423},{"time":1606637040,"reading":0.0191}]}'
```

**Comment by canmor** [comment]
After investigation, I found this issue is because when we implemented this project, we had referenced to both our Java and Ruby version, which has different date/time format in json request, we took an implement of date/time in RFC3339, which's more like Ruby version (actually ISO 8601, slightly different), but we copy our `README.md` from Java version and did not realized this mistake (we thought Java and Ruby implementation are same).

I have amended our `README.md`, thanks for what you dig out, much appreciate.
